dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  version: 1.0.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.129.0
  - gomod: github.com/honeycombio/honeycomb/enhance-indexing-s3-exporter/enhanceindexings3exporter v0.0.0
    path: ./enhanceindexings3exporter

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.129.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.129.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.35.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.35.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.35.0

extensions:
