receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  enhance-indexing-s3-exporter:
    s3uploader:
      region: 'us-east-1'
      s3_bucket: 'my-test-bucket'
      s3_prefix: 'traces-and-logs'

service:
  pipelines:
    logs/objectstorage:
      receivers:
        - otlp
      exporters:
        - enhance-indexing-s3-exporter
    traces/objectstorage:
      receivers:
        - otlp
      exporters:
        - enhance-indexing-s3-exporter